export const operationsWithColors = {
    sent: 'danger',
    receive: 'success',
    transfer: 'success',
    delegatebw: 'danger',
    undelegatebw: 'success',
    buyram: 'danger',
    buyrambytes: 'danger',
    claimrewards: 'danger',
    sellram: 'success',
    voteproducer: 'success',
    newaccount: 'success',
    regproducer: 'success',
    bidname: 'success',
    regproxy: 'danger',
    unregprod: 'success',
    deleteauth: 'danger',
    unlinkauth: 'danger',
    refund: 'success',
    issue: 'grey',
};

export const otherDefaultOps = [
    'updateauth',
    'linkauth',
    'approve',
    'propose',
    'cancel',
    'exec',
    'unapprove'
];

export const systemContract = [
    'eosio',
    'eosio.token',
    'eosio.msig',
    'eosio.ram',
    'eosio.ramfee',
    'eosio.bpay',
    'eosio.vpay',
    'eosio.stake',
    'eosio.savings',
    'eosio.unregd',
    'eosio.wrap',
    'eosio.regram',
    'eosio.names',
    'eosio.null',
];

export const showDataTypes = [
    'setcode',
    'setabi',
    'updateauth',
    'propose',
    'proposal_name',
    'requested',
    'betreceipt',
    'proposer',
    'abi',
    'code',
    'kuai3'
];

export const allOps = [
    'newaccount',
    'transfer',
    'sent',
    'receive',
    'claimrewards',
    'delegatebw',
    'undelegatebw',
    'buyram',
    'buyrambytes',
    'sellram',
    'bidname',
    'voteproducer',
    'regproducer',
    'unregprod',
    'regproxy',
    'updateauth',
    'linkauth',
    'approve',
    'deleteauth',
    'unlinkauth',
    'refund',
    'propose',
    'cancel',
    'exec',
    'unapprove',
    'issue'
];

export const spamTypeList = [
    'broadcast',
    'msg',
    'news',
    'promote',
    'hi',
    'eosabcd',
    'alert',
    'ping',
    'n',
    'u',
    'zh',
    'o',
    'm',
    'push',
    'i',
    'on',
    'event',
    'joinus',
    'topnews',
    'yell',
    'receive'
];

export const spamNameList = [
    'betdicealert',
    'experimentms',
    'message.bank',
    'contractbase',
    'yumgamealert',
    'news.x',
    'eospromoter1',
    '1hello1world',
    'eoseosaddddd',
    'eosblackdrop',
    'eosbaycasino',
    'watchdoggiee',
    'betdiceadmin',
    'candy.pra',
    'eosplayaloud',
    'rockscissors',
    'eospromdress',
    'taketooktook',
    'hirevibeshvt',
    'zkstokensr4u',
    'ethsidechain',
];

export const ops = ['from', 'to', 'info', 'memo', 'message', 'msg', 'id', 'issuer', 'maximum_supply', 'customtoken', 'customasset', 'owner', 'uuid'];
